version: 2.1


develop_filter: &develop_filter
  branches:
    only: develop-legacy

legacy_ota_filter: &legacy_ota_filter
  branches:
    only: release-0.x-legacy

feature_filter: &feature_filter
  branches:
    ignore:
      - master
      - develop
      - develop-legacy
      - release-0.x-legacy
      - stage

orbs:
  node: circleci/node@2.0.1
  slack: circleci/slack@3.2.0
  jq: circleci/jq@2.0.1
  coveralls: coveralls/coveralls@1.0.6

executors:
  node:
    docker:
      - image: circleci/ruby:latest-node
        environment:
          API_URL: $API_URL
          AMPLITUDE_KEY: $AMPLITUDE_KEY
    resource_class: large

commands:
  build:
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle update fastlane
      - run: npm install
  login_to_expo:
    steps:
      - run: npx expo-cli login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      - run: echo "API_URL=$API_URL" > .env
      - run: echo "AMPLITUDE_KEY=$AMPLITUDE_KEY" >> .env
      - run: echo "$GOOGLE_SERVICE_JSON" | base64 --decode > google-services.json
  set_release_channel:
    steps:
      - run:
          name: Set expo release channel
          command: |
            echo 'export RELEASE_CHANNEL=`cat app.json | jq -r '.expo.version' | cut -d. -f1`-$RELEASE_CHANNEL_SUFFIX' >> $BASH_ENV
  publish_to_expo:
    steps:
      - set_release_channel
      - login_to_expo
      - run: npx expo-cli publish --non-interactive --max-workers 1 --release-channel ${RELEASE_CHANNEL}

  legacy_ota_publish:
    steps:
      - login_to_expo
      - run: npx expo-cli publish --non-interactive --max-workers 1 --release-channel 0.9-prod
      - run: npx expo-cli publish --non-interactive --max-workers 1 --release-channel 0.12-prod
      - run: npx expo-cli publish --non-interactive --max-workers 1 --release-channel 0.13-prod
jobs:
  build_and_test:
    executor: node
    working_directory: ~/covid-react
    steps:
      - build
      - run: npm run test:i18n 'sv-SE'
      - run: npm run test:i18n 'es'
      - run: npm run lint
      - run: npm run prettier
      - run: echo "API_URL=" > .env
      - run: echo "AMPLITUDE_KEY=" >> .env
      - run: npm run test:coverage -- --ci
      - coveralls/upload

  develop_deploy:
    executor: node
    working_directory: ~/covid-react
    steps:
      - build
      - publish_to_expo

  legacy_deploy:
    executor: node
    working_directory: ~/covid-react
    steps:
      - build
      - legacy_ota_publish

workflows:
  build_and_test:
    jobs:
      - build_and_test:
          filters: *feature_filter

  develop:
    jobs:
      - build_and_test:
          filters: *develop_filter
      - develop_deploy:
          filters: *develop_filter
          context: react-covid-tracker-dev
          requires:
            - build_and_test

  legacy_ota_release:
    jobs:
      - build_and_test:
          filters: *legacy_ota_filter
      - slack/approval-notification:
          message: Awaiting manual approval to deploy to OTA 0.9-prod, 0.12-prd and 0.13-prod
          context: slack-ci-covid-mobile
          requires:
            - build_and_test
          filters: *legacy_ota_filter
      - wait_for_approval:
          type: approval
          requires:
            - build_and_test
          filters: *legacy_ota_filter
      - legacy_deploy:
          filters: *legacy_ota_filter
          context: react-covid-tracker-prod
          requires:
            - wait_for_approval
